import Tatami.Gen

namespace Tatami

/-! # The relational schema, as SQL

    The design note's Step 2 is a table per nested or repeated substructure,
    with a foreign key linking each back to its parent. `Tatami.Gen` emits that
    correspondence as OCaml; this emits the same `Schema` as the tables
    themselves, so the database is a second copy of one description rather than
    a hand-kept parallel one.

    Both come from `layoutOf`, which is what makes their column order agree by
    construction. Their `db/schema.sql` maintains that agreement in a comment
    today; here it cannot drift.

    Like `Print`, this is a trusted step: a structured value to text, checked by
    reading and by running it. -/

inductive SqlType where
  | bigint      -- our `int` reaches 2^62, past what `integer` holds
  | doublePrec
  | text
  | uuid
  | boolean
  deriving Repr, DecidableEq

def SqlType.print : SqlType → String
  | .bigint => "bigint"
  | .doublePrec => "double precision"
  | .text => "text"
  | .uuid => "uuid"
  | .boolean => "boolean"

structure SqlColumn where
  name : String
  ty : SqlType
  notNull : Bool
  primaryKey : Bool := false
  /-- the table this column is a key into, if it is one -/
  references : Option String := none
  deriving Repr

structure SqlTable where
  name : String
  columns : List SqlColumn
  deriving Repr

abbrev Ddl := List SqlTable

/-- A member's type as a column's type.

    `bot` is a member seen only as `null`, so nothing is known about what it
    would hold. It becomes `text` and is always null, which is the one shape
    that cannot be wrong. -/
def sqlTypeOf : Ty → SqlType
  | .int => .bigint
  | .float => .doublePrec
  | .str => .text
  | .uuid => .uuid
  | .bool => .boolean
  | .bot => .text
  | .ref _ => .text      -- replaced by the target's key type; see `resolve`
  | .coll _ => .text     -- never a column

/-- A key is stored the way the thing it points at is stored, which is in
    another table, so it can only be settled once every table is laid out. -/
private def keyTypeOf (layouts : List (Path × List Col)) (p : Path) : SqlType :=
  match layouts.lookup p with
  | some (c :: _) => sqlTypeOf c.ty
  | _ => .bigint

def genDdl (root : String) (s : Schema) : Except Error Ddl := do
  let ordered := orderTables s
  let mut layouts : List (Path × List Col) := []
  for t in ordered do
    layouts := layouts ++ [(t.path, ← layoutOf root t)]
  let mut tables : Ddl := []
  for t in ordered do
    let cols := (layouts.lookup t.path).getD []
    tables := tables ++ [{
      name := (moduleName root t.path).toLower
      columns := cols.map fun c =>
        { name := c.name
        , ty := match c.ty with | .ref p => keyTypeOf layouts p | ty => sqlTypeOf ty
        , notNull := !c.nullable
        , primaryKey := c.isKey
        , references := match c.ty with
            | .ref p => some (moduleName root p).toLower
            | _ => none } }]
  return tables

/-- `CREATE TABLE`, in the order the tables are emitted, which is also an order
    in which each table's references already exist.

    The foreign keys are not here: they go on after the rows are in, because
    validating them one row at a time during a bulk load would dominate it. -/
def Ddl.printSchema (d : Ddl) : String :=
  let drops :=
    if d.isEmpty then ""
    else "DROP TABLE IF EXISTS " ++ String.intercalate ", " (d.reverse.map (·.name)) ++ " CASCADE;\n\n"
  let width (t : SqlTable) : Nat :=
    t.columns.foldl (fun w c => max w c.name.length) 0
  let table (t : SqlTable) : String :=
    let w := width t
    let body := String.intercalate ",\n" (t.columns.map fun c =>
      let pad := String.mk (List.replicate (w - c.name.length) ' ')
      let ty := c.ty.print
      let tyPad := String.mk (List.replicate (max 1 (17 - ty.length)) ' ')
      "  " ++ c.name ++ pad ++ " " ++ ty ++
        (if c.primaryKey then tyPad ++ "PRIMARY KEY"
         else if c.notNull then tyPad ++ "NOT NULL" else ""))
    s!"CREATE TABLE {t.name} (\n{body}\n);"
  "-- Generated by tatami. Column order and nullability follow the .mli files:\n" ++
  "-- NOT NULL appears exactly where the signature does not say `option`.\n\n" ++
  drops ++ String.intercalate "\n\n" (d.map table) ++ "\n"

/-- The references, and the indexes a join across the nesting needs.

    Applied after the rows are in. A three-hop join follows these keys, so
    without the indexes it is three sequential scans and any measurement taken
    over it is about the missing index rather than anything else. -/
def Ddl.printConstraints (d : Ddl) : String :=
  let keys := d.flatMap fun t =>
    t.columns.filterMap fun c => c.references.map fun target => (t.name, c.name, target)
  if keys.isEmpty then
    "-- Generated by tatami. No table references another.\n"
  else
    let pk (target : String) : String :=
      match (d.find? (·.name == target)).bind (·.columns.find? (·.primaryKey)) with
      | some c => c.name
      | none => "id"
    let alters := keys.map fun (t, c, target) =>
      s!"ALTER TABLE {t} ADD CONSTRAINT {t}_{target}_fk FOREIGN KEY ({c}) REFERENCES {target} ({pk target});"
    let indexes := keys.map fun (t, c, _) =>
      s!"CREATE INDEX {t}_{c}_idx ON {t} ({c});"
    "-- Generated by tatami. Applied after the COPY: validating every row on\n" ++
    "-- the way in would dominate a bulk load.\n\n" ++
    String.intercalate "\n" alters ++
    "\n\n-- A join across the nesting follows these keys.\n\n" ++
    String.intercalate "\n" indexes ++ "\n\nANALYZE;\n"

/-- The three steps, with the table list read from `tables` rather than written
    into the script. Everything goes through stdin so the same script works
    against a local `psql` and against one inside a container. -/
def Ddl.printLoader (_d : Ddl) : String :=
  "#!/bin/sh\n" ++
  "# Generated by tatami. Load the shredded corpus into Postgres.\n" ++
  "#\n" ++
  "#   sh load.sh\n" ++
  "#   PSQL='docker exec -i tatami-pg psql -qXU tatami -d tatami' sh load.sh\n" ++
  "#\n" ++
  "# Tables are created empty, filled by COPY, and only then given their\n" ++
  "# foreign keys and indexes: validating every row on the way in would\n" ++
  "# dominate the load, and afterwards they are checked once, in bulk.\n" ++
  "set -eu\n" ++
  "cd \"$(dirname \"$0\")\"\n" ++
  "PSQL=${PSQL:-psql}\n\n" ++
  "echo 'creating tables'\n" ++
  "$PSQL -v ON_ERROR_STOP=1 -q < schema.sql\n\n" ++
  "# </dev/null below matters: a command in a read loop that does not redirect\n" ++
  "# its stdin consumes the rest of the list it is reading.\n" ++
  "while read -r t; do\n" ++
  "  [ -f \"$t.tsv\" ] || { echo \"$t.tsv is missing -- rerun with --data\" >&2; exit 1; }\n" ++
  "  printf '  copy %-24s' \"$t\"\n" ++
  "  $PSQL -v ON_ERROR_STOP=1 -qXAt -c \"COPY $t FROM STDIN\" < \"$t.tsv\"\n" ++
  "  $PSQL -qXAt -c \"select count(*) from $t\" < /dev/null\n" ++
  "done < tables\n\n" ++
  "echo 'foreign keys and indexes'\n" ++
  "$PSQL -v ON_ERROR_STOP=1 -q < constraints.sql\n" ++
  "echo done\n"

/-- The tables in load order, one per line: what a loader needs and the one
    thing it should not have to hardcode. -/
def Ddl.printTables (d : Ddl) : String :=
  String.intercalate "\n" (d.map (·.name)) ++ "\n"

end Tatami
